# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 453)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:rgb(36, 31, 49);\n"
"color:rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Time = QtWidgets.QLabel(self.centralwidget)
        self.Time.setMaximumSize(QtCore.QSize(500, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Time.setFont(font)
        self.Time.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Time.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Time.setAlignment(QtCore.Qt.AlignCenter)
        self.Time.setObjectName("Time")
        self.verticalLayout.addWidget(self.Time)
        self.User_time = QtWidgets.QLineEdit(self.centralwidget)
        self.User_time.setText("")
        self.User_time.setObjectName("User_time")
        self.verticalLayout.addWidget(self.User_time)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pause_btn = QtWidgets.QPushButton(self.centralwidget)
        self.pause_btn.setObjectName("pause_btn")
        self.verticalLayout.addWidget(self.pause_btn)
        self.reset_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reset_btn.setObjectName("reset_btn")
        self.verticalLayout.addWidget(self.reset_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Timer"))
        self.Time.setText(_translate("MainWindow", "00:00"))
        self.User_time.setPlaceholderText(_translate("MainWindow", "Enter the time"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pause_btn.setText(_translate("MainWindow", "Pause"))
        self.reset_btn.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
